### Chapter 01 Basic Python

In [ ]:
import time
from ast import parse
from distutils.command.install import value
from itertools import product, groupby
from logging import exception, info

import pandas
from IPython.core.completerlib import import_re
from PIL.ImageOps import flip
from fontTools.diff import color
from fontTools.subset import subset
from fontTools.varLib.instancer import names
from jupyter_client.jsonutil import parse_date
from numpy.conftest import dtype
from pandas import DataFrame
from pandas._libs.tslibs import vectorized
from pip._internal.commands import index
from pygments.lexers import data

print("Hello world")

#### Data Types

In [ ]:
#integer
print(42)

print(1e309) #this will print 'inf' because it exceeds the float limit

In [ ]:
#float
print(3.14159)

print(1.7e308) #this will print '1.7e+308' because it is within the float limit

In [ ]:
#boolean
print(True)
print(False)

In [ ]:
#text
print("welcome to Uet Peshawar")

In [ ]:
#complex
print(3 + 4j)

In [ ]:
#List
print([1, 2, 3, 4, 5])

In [ ]:
#tuple
print((1, 2, 3, 4, 5))

In [ ]:
#dictionary
print({'name': 'mudasir', 'age': 18})

In [ ]:
#set
print({1, 2, 3, 4, 5})

In [ ]:
#type
type(42)

### varibales

In [ ]:
# Dynamic typing vs Static typing
# Dynamic binding vs Static binding
# stylish diclaration techniques

In [ ]:
#dynamic typing
x = 10
print(x)

#static typeing (using in other languages like C, Java)
int y = 20

In [ ]:
#dynamic binding (you can change the type of variable in python in the same program)
x = "hello"
print(x)
x = 'mudasir'
print(x)

#static binding (using in other languages like C, Java you cannot change the type of variable in the same program)
int z = 30

In [ ]:
a = 5
b = 10
c = 5
print(a,b,c)

a,b,c = 5,10,5
print(a,b,c)

In [ ]:
a=b=c=100
print(a,b,c)

### User Input

In [ ]:
#static vs dynamic

input("Enter your name: ")

In [ ]:
#take input from user and store it in a variable


fnum = input("Enter first number: ")
snum = input("Enter second number: ")
#print(type(fnum), type(snum))
#add two numbers
result = int(fnum) + int(snum)
# print the result
print (result)
print(type(fnum))

### Type Conversion

In [ ]:
#implicit vs explicit type conversion
#implicit type conversion
print(5 + 2.0)
print(type(5),type(2.0))

In [ ]:
# Explicit
# int -> str

#int(4+5j)  

# str
str(5)

# float
float(4)

### operators in python

In [ ]:
# arithmetic operations
# Relational operators
# Logical operators
# Bitwise operators
# assignment operators
# membership operators

In [ ]:
# Arithmetic operators
print(5 + 2)    # addition
print(5 - 2)    # subtraction
print(5 * 2)    # multiplication
print(5 / 2)    # division
print(5 // 2)   # floor division
print(5 % 2)    # modulus
print(5 ** 2)   # exponentiation

In [ ]:
# Relational operators
print(5 > 2)    # greater than
print(5 < 2)    # less than
print(5 >= 5)   # greater than or equal to
print(5 <= 5)   # less than or equal to
print(5 == 5)   # equal to
print(5 != 5)   # not equal to

In [ ]:
# Logical operators
print(1 and 0)    # logical AND
print(1 or 0)     # logical OR
print(not 1)      # logical NOT

In [ ]:
# bitwise operators
print(5 & 3)    # bitwise AND
print(5 | 3)    # bitwise OR
print(5 ^ 3)    # bitwise XOR
print(~5)       # bitwise NOT
print(5 << 1)  # left shift
print(5 >> 1)  # right shift

In [ ]:
# Assignment operators
# =
# a = 5

a = 5
# a = a + 5
a += 5  # equivalent to a = a + 5
print(a)

In [ ]:
# membership operators
print('a' in 'apple')

print(1 in [2, 3, 4, 5])

### if else in python

In [ ]:
# login form 
# email -> mudai079@gmail.com
# password -> mudasir123

email = input("Enter your email: ")
password = input("Enter your password: ")

if email == "mudai079@gmail.com" and password == "mudasir123":
  print("welcome mudasir")
elif email == "mudai079@gmail.com" and password != "mudasir123":
 # tell the user
    print("incorrect password")
    password = input("Please re-enter your password: ")
    if password == "mudasir123":
        print("welcome mudasir")
    else:
        print("beta tum se na ho payega")
else:
    print("incorrect email")

In [ ]:
# main of 3 numbers

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a<b and a<c:
    print('smallest number is:',a)
elif b<a and b<c:
    print('smallest number is:',b)
else:
    print('smallest number is:',c)

In [ ]:
# menu driven calculator

fnum = int(input("Enter first number: "))
snum = int(input("Enter second number: "))

op = input("Enter operator (+, -, *, /): ")
if op == '+':
    print("Result:", fnum + snum)
elif op == '-':
    print("Result:", fnum - snum)
elif op == '*':
    print("Result:", fnum * snum)
elif op == '/':
    if snum != 0:
        print("Result:", fnum / snum)
    else:
        print("Error: Division by zero")
else:
    print("Invalid operator")

### Modules in python

#### . math
#### . keyword
#### . random
#### . datetime

In [ ]:
# math
import math
print(math.sqrt(16))
print(math.factorial(5))
print(math.factorial(7))

In [ ]:
# keywords
import keyword
print(keyword.kwlist)

In [ ]:
# random
import random
print(random.randint(1, 100))

In [ ]:
# datetime
import datetime
print(datetime.datetime.now())

### Loops
### . Need for loop
### . While loop
### . For loop

In [ ]:
# While loop
number = int(input("Enter a number: "))
i = 1
while i < 11:
    print(number, '*',i, '=',number * i)
    i += 1

In [1]:
# while loop with else
x = 1
while x < 5:
    print(x)
    x += 1
else:
    print("Loop ended")

1
2
3
4
Loop ended

In [ ]:
# generat a random number between 1 and 100 until the user guesses it
import random
jackpot_number = random.randint(1, 100)

guess = int(input("guess karo: "))
counter = 1
while guess != jackpot_number:
    if guess < jackpot_number:
        print("too low")
    else:
        print("too high")
    guess = int(input("guess karo: "))
    counter += 1
else:
    print("congratulations! you guessed it in", counter, "tries")
    print("attemmpts", counter)

In [ ]:
# For loop demo
# for i in range(1, 11):
#     print(i)

for i in range(1, 11,2):
    print(i)

In [3]:
currn_pop = 10000
for i in range(10 ,0 ,-1):
    print(i, currn_pop)
    currn_pop = currn_pop/1.1

10 10000
9 9090.90909090909
8 8264.462809917353
7 7513.148009015775
6 6830.134553650703
5 6209.213230591548
4 5644.739300537771
3 5131.5811823070635
2 4665.07380209733
1 4240.976183724845

### sequence Sum

1/3! + 2/2! + 3/3!+.......

In [ ]:
# code here
n = int(input("Enter n"))

result = 0
fact = 1

for i in range(1,n+1):
    fact = fact * i
    result = result + 1/fact

print(result)

### Nested Loop

In [2]:
# 1 Example
for i in range(1,6):
  for j in range(1,6):
        print(i,j)

1 1
1 2
1 3
1 4
1 5
2 1
2 2
2 3
2 4
2 5
3 1
3 2
3 3
3 4
3 5
4 1
4 2
4 3
4 4
4 5
5 1
5 2
5 3
5 4
5 5

### pattern 1

# *
# **
# ***
# ****

In [1]:
rows = int(input("Enter number of rows: "))
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print("*", end=" ")
    print()

*
* *
* * *
* * * *
* * * * *

In [2]:
rows = int(input("Enter number of rows: "))

for i in range(1, rows + 1):
    for space in range(rows - i):
        print(" ", end="")
    for star in range(2 * i - 1):
        print("*", end="")
    print()

    *
   ***
  *****
 *******
*********

In [3]:
rows = int(input("Enter number of rows: "))
for i in range (1, rows + 1):
    for j in range (1, i + 1):
        print(j, end=" ")
    for k in range (i -1, 0, -1):
        print(k, end=" ")
    print()

1
1 2 1
1 2 3 2 1
1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1

### Loop Control Statment
#### .Break
#### .Continue
#### .pass

In [4]:
# break Statement
for i in range(1, 11):
    if i == 6:
        break
    print(i)

1
2
3
4
5

In [5]:
lower = int(input("Enter lower range: "))
upper = int(input("Enter upper range: "))
for i in range(lower, upper + 1):
    for j in range(2, i):
        if i % j == 0:
            break
    else:
        print(i)

5
7
11
13
17
19
23
29
31
37
41
43
47

In [6]:
#continue Statement
for i in range(1, 11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10

In [8]:
#pass Statement
for i in range(1, 6):
    pass

### string are the sequence of characters
#### .creating string
#### .accessing string
#### .adding char to string
#### .editing string
#### .deleting string
#### .operation on strings
#### .string function

In [9]:
# creating strings
s = "Hello, World!"
s = 'Python is awesome'
s = """This is a multi-line string."""
print(s)

This is a multi-line string.

### Accessing Strings

In [14]:
#postive indexing
s = 'hello world'
print(s[6])

w

In [15]:
#negative indexing
s = 'hello world'
print(s[-3])

r

In [16]:
#slicing
s = 'hello world'
print(s[0:8])

hello wo

In [17]:
s = 'hello world'
print(s[-1 : -6 : -1])

dlrow

#### Editing and deleted strings

In [18]:
s = 'hello world'
s[0] = 'H'  # This will raise an error because strings are immutable

TypeError: 'str' object does not support item assignment

### Operation on strings
##### .Arithmetic Operators
##### .Relational Operators
##### .Logical Operators
##### .Loops in Strings
##### .Membership Operators

In [19]:
print('peshawar' + ' ' + 'lahore')

peshawar lahore

In [20]:
print('peshawar'*6)

peshawarpeshawarpeshawarpeshawarpeshawarpeshawar

In [21]:
print('*'*40)

****************************************

#### Relational Operators

In [22]:
'lahore' != 'lahore'

False

#### Logical Operators

In [24]:
'' or 'world'

'world'

In [23]:
'hello' or 'world'

'hello'

### Functions

In [4]:
def great():
    print("helllo world")
great()

helllo world

In [5]:
def great(name):
    print("AOA",name)
great("Mudasir")

AOA Mudasir

In [2]:
def is_even(num):
    '''
    this function returns if a given number is even or odd
    input - any valid number
    output - odd/even
    created by mudasir
    created on 12-02-2026

    '''
    if type(num) == int:
       if num % 2 == 0:
        return "even"
       else:
        return "odd"
    else:
        return "pagal hai keya"

In [4]:
#function
for i in range(1, 11):
    x = is_even(i)
    print(x)

odd
even
odd
even
odd
even
odd
even
odd
even

In [9]:
is_even('hello')

'pagal hai keya'

### Parameter vs Arguments

### Types of Arguments
#### Default argument
#### positional argument
#### Keyword argument

In [4]:
#default argument
def power(a=1,b=1):
    return a**b

In [5]:
power(2,3)

8

In [7]:
#position argument
power(2,3)

8

In [9]:
#keyword argument
power(b=3,a=2)

8

### *args and **kwargs
#### *args and **kwargs
are special python keywords that are used to pass to variable length of arguments to a function

In [21]:
# *agrs
def multiply(*args):
    product = 1
    for i in args:
        product = product * i
    return product

In [24]:
multiply(1,2,3,4,2,34,344,34,43,4,3555,23)

268443814901760

In [26]:
#**kwargs
def display(**kwargs):
    for (key, value) in kwargs.items():
        print(key,'->',value)

In [29]:
display(pakistan = 'islamabad', india = 'delhi', srilanka = 'colombo')

pakistan -> islamabad
india -> delhi
srilanka -> colombo

### OOP

#### class and object

In [8]:
class car:
    def drive(self):
        print("car is moving")
car1 = car()
car1.drive()

car is moving

In [10]:
class car:
    color ="red"
    def drive(self):
        print(f"{self.color} car is moving")
car1 = car()
car1.drive()

red car is moving

In [11]:
class car:
    color = "red"
    def drive(self):
        print(f"{self.color} car is moving")
    def setcolor(self,new_color):
        self.color = new_color
car2 = car()
car2.setcolor("yellow")
car2.drive()

yellow car is moving

#### constructor

In [13]:
class Dog:
    def __init__(self):
        self.name = "Buddy"
    def bark(self):
            print(f"{self.name} say woof")
dog1 = Dog()
dog1.bark()

Buddy say woof

In [17]:
class car:
    def __init__(self, brand , color):
        self.brand = brand
        self.color = color
car1= car("BMW","white")
print(car1.brand)
print(car1.color)

BMW
white

In [19]:
car1.color = "red"
car2= car("honda","white")
print(car2.brand)
print(car2.color)
print(car1.color)

honda
white
red

#### instance veriable

In [46]:
class student:
    def __init__(self,name,age,grade):
        self.name = name
        self.age = age
        self.grade = grade
    def display_info(self):
        print(f"student Name:{self.name}")
        print(f"student Age: {self.age}")
        print(f"student Grade: {self.grade}")

    def is_eligible(self):
        if self.age >= 18:
            print(self.name,"is eligible for admission)")
        else:
            print(self.name,"is not eligible for admission")

In [51]:
student1 = student("mudasir",20,"12th")
student2 = student("huzaifa",17,"11th")

In [52]:
print(student1.name)
print(student2.grade)

mudasir
11th

In [53]:
student1.display_info()
student1.is_eligible()

student Name:mudasir
student Age: 20
student Grade: 12th
mudasir is eligible for admission)

In [54]:
student2.display_info()
student2.is_eligible()

student Name:huzaifa
student Age: 17
student Grade: 11th
huzaifa is not eligible for admission

### inheritance

In [1]:
class Animal:
    def speak(self):
        print("some sound")

In [18]:
class Dog(Animal):
    pass

In [3]:
dog1 = Dog()

In [ ]:
dog1.speak()

In [4]:
class Dog(Animal):
    def bark(self):
        print("woof")

In [5]:
childdog = Dog()

In [6]:
childdog.bark()

woof

In [7]:
childdog.speak()

some sound

#### Method overriding

In [28]:
class Animal:
    def speak(self):
        print("some sound")

In [30]:
class Dog(Animal):
    def speak(self):
        print("woof! woof!")

In [31]:
dog1 = Dog()

In [32]:
dog1.speak()

woof! woof!

### polymorphism

In [1]:
class Dog:
    def speak(self):
        print("woof")

In [3]:
class cat:
    def speak(self):
        print("meow")

In [9]:
for pet in (Dog(),cat()):
    pet.speak()

woof
meow

#### method overriding in polymorphism

In [10]:
class vehicle:
    def move(self):
        print("vehicle is moving")

In [11]:
class car(vehicle):
    def move(self):
        print("car is draving")

In [12]:
car1=car()

In [13]:
car1.move()

car is draving

In [17]:
class calculator:
    def add(self,a,b=0,c=0):
        return (a+b+c)

In [18]:
calc1=calculator()

In [19]:
print(calc1.add(5))

5

In [20]:
print(calc1.add(5,6))

11

In [21]:
print(calc1.add(5,6,7))

18

### file handling

In [22]:
file1= open("demo.txt","r")

In [23]:
print(file1.read())

welcome

In [24]:
file1.close()

In [25]:
file1=open("demo.txt","w")

In [26]:
file1.write("welcome to uet")

14

In [27]:
file1.close()

In [35]:
file1=open("demo.txt","a")

In [39]:
file1.write("\n And also welcome to zalalat zindagi")

37

In [40]:
file1.close()

#### use try,except,else,& finally block

In [1]:
num = int(input("enter a number"))
print(10/num)

2.0

In [59]:
try:
    num = int(input("enter a number: "))
    print(10/ num)
except zeroDivisionError:
    print("you can't divide by zero!")
except valueError:
    print("that's not a number")
except Exception as e:
    print(f"unexcepted error occurred: {e}")

3.3333333333333335

### Libraries

#### numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [5]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]

In [7]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]

In [8]:
print(np.full((2,3),4))

[[4 4 4]
 [4 4 4]]

In [13]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]

In [17]:
print(np.linspace(1,5,7))

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]

In [18]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [20]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]

In [22]:
print(np.array([1,5,3],dtype=float))

[1. 5. 3.]

In [23]:
arr=np.array([1.3,2.7,3.5])
print(arr.astype(int))

[1 2 3]

In [5]:
import numpy as np

In [14]:
rng = np.random.default_rng(seed=34)
flips = rng.integers(0,2,size=10000)
prob_head = np.mean(flips)
print("estimated probability of heads:",prob_head)

estimated probability of heads: 0.5028

In [19]:
import time
#pyhton loop
start = time.time()
squares = [i**2 for i in range(1000000)]
end = time.time()
print("loop time:",end-start)

# numpy vectorized
start = time.time()
arr = np.arange(1000000)
squares_np= arr**2
end = time.time()
print("victorized time:",end-start)

loop time: 0.8599975109100342
victorized time: 0.01300048828125

### pandas

In [1]:
import pandas as pd

In [8]:
s = pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
print('value:',s.values)
print('index:',s.index)
print('dtype:',s.dtype)

value: [10 20 30 40 50]
index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
dtype: int64

In [10]:
print(s.head)

<bound method NDFrame.head of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [11]:
print(s.tail)

<bound method NDFrame.tail of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [12]:
print(s.value_counts())

10    1
20    1
30    1
40    1
50    1
Name: count, dtype: int64

In [13]:
data={
    'Name': ['mudasir','huzaifa','waqas'],
    'Age' : [20,21,23],
    'city': ['hangu','dir','kohat'],
}
df = pd.DataFrame(data)
print(df)

      Name  Age   city
0  mudasir   20  hangu
1  huzaifa   21    dir
2    waqas   23  kohat

In [14]:
df = pd.read_csv('retail_sales.csv')
print("info:\n",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB
info:
 None

In [20]:
print("\nshape:",df.shape)
print("\nData Types:\n",df.dtypes)

shape: (1825, 6)

Data Types:
 Date         object
Category     object
Sales       float64
Quantity    float64
Profit      float64
Region       object
dtype: object

In [23]:
print("\nStatistical summary:\n",df.describe())

Statistical summary:
              Sales     Quantity       Profit
count  1823.000000  1820.000000  1825.000000
mean    980.482677    10.053846   248.696130
std     336.756618     5.515370   118.159627
min       0.000000     0.000000     0.000000
25%     784.071354     5.000000   156.916498
50%     997.725134    10.000000   229.344557
75%    1208.512721    15.000000   324.867847
max    1888.932537    19.000000   703.228418

In [26]:
data={
    'Name': ['mudasir','huzaifa','waqas','qari'],
    'Age' : [20,21,23,18],
    'city': ['hangu','dir','kohat', 'orakzai'],
    'salary': [1000000,20000,140000,120000,]
}
df = pd.DataFrame(data)
print("original DataFrame:\n",df)

original DataFrame:
       Name  Age     city   salary
0  mudasir   20    hangu  1000000
1  huzaifa   21      dir    20000
2    waqas   23    kohat   140000
3     qari   18  orakzai   120000

In [29]:
subset_loc = df.loc[1:3,['Name','salary']]
print("subset with .loc:\n",subset_loc)

subset with .loc:
       Name  salary
1  huzaifa   20000
2    waqas  140000
3     qari  120000

In [30]:
subset_iloc= df.iloc[0:2,1:3]
print("subset with .iloc:\n",subset_iloc)

subset with .iloc:
    Age   city
0   20  hangu
1   21    dir

In [31]:
high_salary = df[df['salary']>75000]
print("high salary:\n",high_salary)

high salary:
       Name  Age     city   salary
0  mudasir   20    hangu  1000000
2    waqas   23    kohat   140000
3     qari   18  orakzai   120000

In [33]:
df.loc[df['Age']<30,'salary'] = 100000
print("low Age salary change\n",df.loc[df['Age']<30,'salary'])

low Age salary change
 0    100000
1    100000
2    100000
3    100000
Name: salary, dtype: int64

In [36]:
df = pd.read_csv("retail_sales.csv")
parse_dates=['Date']
dtype={
    "category": "category",
}
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB

In [39]:
df['Profit'] = pd.to_numeric(df['Profit'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB

In [41]:
df['Region'] = df['Region'].astype('category')
df.info()
print(df['Region'].memory_usage(deep=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(1), float64(3), object(2)
memory usage: 73.4+ KB
2431

In [8]:
import pandas as pd

In [9]:
df= pd.DataFrame({
     'Category': ['Electronic','furniture','Home-Appliances','electronic']
})
print(df)

          Category
0       Electronic
1        furniture
2  Home-Appliances
3       electronic

In [11]:
df['Category_clean']= df['Category'].str.strip().str.lower()
print(df)

          Category   Category_clean
0       Electronic       electronic
1        furniture        furniture
2  Home-Appliances  home-appliances
3       electronic       electronic

In [12]:
df['Category_clean'] = df['Category_clean'].str.replace('-',' ')
print(df)

          Category   Category_clean
0       Electronic       electronic
1        furniture        furniture
2  Home-Appliances  home appliances
3       electronic       electronic

In [14]:
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=['Date'],
    dtype={
        "Category": "category",
        "Region": "category",
    }
)
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [16]:
df_sorted =df.sort_values(by=['Quantity','Sales'],ascending=[False,True])
print("sorted the DataFrame")
df_sorted.head()

sorted the DataFrame

           Date    Category       Sales  Quantity      Profit Region
312  2023-03-04  Home Goods    0.000000      19.0    0.000000   West
528  2023-04-16      Sports    0.000000      19.0  270.577388   West
1708 2023-12-08      Sports  227.942727      19.0   61.534381  North
571  2023-04-25    Clothing  361.006937      19.0   57.285585   West
1213 2023-08-31      Sports  368.305917      19.0   73.419555   West

In [18]:
df['Sales_rank']=df.groupby('Quantity')['Sales'].rank(method='dense',ascending=False)
print("\n rank within Quantity Groups:\n",df)

 rank within Quantity Groups:
            Date     Category        Sales  Quantity      Profit Region  \
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

      Sales_rank
0           29.0
1           56.0
2            7.0
3           24.0
4           68.0
...          ...
1820        30.0
1821        88.0
1822        32.0
1823        38.0
1824        73.0

[1825 rows x 7 columns]

In [29]:
customers = pd.DataFrame({
    'CustomerID':[1,2,3],
    'Name':['Mudasir','huzaifa','waqas'],
})
orders = pd.DataFrame({
    'CustomerID':[1,2,3,3,4,5],
    'orderID':[1,2,3,4,5,6],
    'Amount':[250,300,400,100,150,200],
})

In [30]:
df_inner = pd.merge(customers,orders,on='CustomerID',how='inner')
print("inner Merge:\n",df_inner)

inner Merge:
    CustomerID     Name  orderID  Amount
0           1  Mudasir        1     250
1           2  huzaifa        2     300
2           3    waqas        3     400
3           3    waqas        4     100

In [31]:
df_left = pd.merge(customers,orders,on='CustomerID',how='left')
print("left Merge:\n",df_left)

left Merge:
    CustomerID     Name  orderID  Amount
0           1  Mudasir        1     250
1           2  huzaifa        2     300
2           3    waqas        3     400
3           3    waqas        4     100

In [34]:
de_concat = pd.concat([customers,customers])
print(("\nConcatenated Row:\n",de_concat))

('\nConcatenated Row:\n',    CustomerID     Name
0           1  Mudasir
1           2  huzaifa
2           3    waqas
0           1  Mudasir
1           2  huzaifa
2           3    waqas)

In [5]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv")

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [20]:
df ["payment_type"] =df["payment_method"].map({
     'Card': 'Digital',
    'Wallet': 'Digital',
    'COD': 'cash'
})

In [21]:
df ['payment_type'].unique()

array(['Digital', 'cash'], dtype=object)

In [22]:
df[['payment_type','payment_method']].head()

  payment_type payment_method
0      Digital         Wallet
1      Digital           Card
2         cash            COD
3      Digital         Wallet
4      Digital         Wallet

In [23]:
df.groupby('payment_type').size()

payment_type
Digital    3226
cash       1774
dtype: int64

In [2]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv",parse_dates=['order_date'])

In [5]:
numaric_df = df[["quantity","unit_price","discount","delivery_days","revenue"]]
print("\ncoveriance:\n",numaric_df.cov())

coveriance:
                   quantity    unit_price   discount  delivery_days  \
quantity          4.082009      0.512237  -0.000881      -0.055733
unit_price        0.512237  28648.733946   0.226823       8.338403
discount         -0.000881      0.226823   0.010283      -0.000122
delivery_days    -0.055733      8.338403  -0.000122       9.943075
revenue        1040.110589  94746.795528 -11.661466      14.172711

                     revenue
quantity         1040.110589
unit_price      94746.795528
discount          -11.661466
delivery_days      14.172711
revenue        681589.302978

In [6]:
print("\ncorrelation:\n",numaric_df.corr())

correlation:
                quantity  unit_price  discount  delivery_days   revenue
quantity       1.000000    0.001498 -0.004302      -0.008748  0.623564
unit_price     0.001498    1.000000  0.013215       0.015623  0.678032
discount      -0.004302    0.013215  1.000000      -0.000382 -0.139296
delivery_days -0.008748    0.015623 -0.000382       1.000000  0.005444
revenue        0.623564    0.678032 -0.139296       0.005444  1.000000